import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline': '#8c928b',
        'inverse-primary': '#4a654e',
        'on-tertiary-fixed-variant': '#574500',
        'on-primary-fixed': '#07200f',
        'surface-bright': '#353941',
        'on-secondary-fixed': '#2a1617',
        'secondary': '#e2bebe',
        'surface-container-highest': '#30353d',
        'on-surface-variant': '#c2c8c0',
        'background': '#0f141a',
        'secondary-fixed': '#ffdada',
        'error': '#ffb4ab',
        'surface-tint': '#b0ceb2',
        'primary': '#b0ceb2',
        'primary-fixed': '#cceace',
        'secondary-fixed-dim': '#e2bebe',
        'on-surface': '#dee2ec',
        'surface-container-high': '#252a32',
        'on-primary': '#1c3622',
        'tertiary-fixed': '#ffe088',
        'on-error': '#690005',
        'tertiary-container': '#c09d25',
        'inverse-on-surface': '#2c3138',
        'on-tertiary-container': '#453600',
        'primary-fixed-dim': '#b0ceb2',
        'on-tertiary-fixed': '#241a00',
        'surface-container-low': '#171c23',
        'on-primary-container': '#233d29',
        'on-secondary-container': '#d0adad',
        'inverse-surface': '#dee2ec',
        'on-primary-fixed-variant': '#334d38',
        'surface-container-lowest': '#090f15',
        'on-tertiary': '#3c2f00',
        'primary-container': '#8ba88e',
        'surface': '#0f141a',
        'on-secondary-fixed-variant': '#5a4041',
        'surface-variant': '#30353d',
        'on-background': '#dee2ec',
        'secondary-container': '#5a4041',
        'surface-dim': '#0f141a',
        'error-container': '#93000a',
        'outline-variant': '#424842',
        'tertiary-fixed-dim': '#e9c349',
        'on-secondary': '#412a2b',
        'tertiary': '#e9c349',
        'surface-container': '#1b2027',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '12px',
        'container-padding': '20px',
        unit: '4px',
      },
      fontFamily: {
        'headline-xl': ['Newsreader', 'serif'],
        'headline-lg': ['Newsreader', 'serif'],
        'headline-md': ['Newsreader', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.25', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

export default config
